apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
  labels:
    app: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: public.ecr.aws/v6b3r3l0/accuknox-project-saloni:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 4499
